//Login Actions 
export const LOGIN_INITIAL = 'LOGIN_INITIAL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL'

//GET SUBMISSION DETAILS
export const GET_SUBMISSION_DETAILS_INITIAL ="GET_SUBMISSION_DETAILS_INITIAL"
export const GET_SUBMISSION_DETAILS_SUCCESS ="GET_SUBMISSION_DETAILS_SUCCESS"
export const GET_SUBMISSION_DETAILS_FAIL ="GET_SUBMISSION_DETAILS_FAIL"
export const GET_SUBMISSION_DETAILS_NETWORK_ERROR="GET_SUBMISSION_DETAILS_NETWORK_ERROR"

//View Employee Details
export const VIEW_EMPLOYEE_DETAILS_INITIAL ="VIEW_EMPLOYEE_DETAILS_INITIAL"
export const VIEW_EMPLOYEE_DETAILS_SUCCESS ="VIEW_EMPLOYEE_DETAILS_SUCCESS"
export const VIEW_EMPLOYEE_DETAILS_FAIL ="VIEW_EMPLOYEE_DETAILS_FAIL"
export const VIEW_EMPLOYEE_DETAILS_NETWORK_ERROR="VIEW_EMPLOYEE_DETAILS_NETWORK_ERROR"
